name = "Prezo"
uuid = "b8def1d8-96d4-4d03-b88c-856be0d8edff"
version = "0.1.0"
authors = ["Tyler Brough <broughtj@gmail.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.118"
Documenter = "1.15.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.11"
Random = "1.11.0"
Statistics = "1.11.1"
Test = "1.11.0"
